### ISSUE TITLE
result not equal BouncyCastleProvider

### ISSUE THREAD

**Issue by vast-z** [C0MM4ND/dart-secp256k1#1]
Thank you very much, I really need this library, but the string after the hash is signed with the private key is different every time. I don’t know the principle, can you help me?

**Comment by c0mm4nd** [comment]
this is a signature curve not for hashing. I cannot understand why you need the consistent result. 

I havent used java nor BouncyCastle. As far as I known, the dart port of this, pointycastle, doesnt have secp256k1 support.

The reason why different every time is here https://github.com/C0MM4ND/dart-secp256k1/blob/72182100d5445b23bae633bfa4e10e4c94614bf9/lib/src/base.dart#L217 

Please briefly describe your actual demand and then I am able to help you.

**Comment by c0mm4nd** [comment]
Close this issue because no further reply
